// Static data mirroring catalog.ts / stores.ts / products.ts
// (brands, stores, deals, coupons, sale_events — everything except
// products/offers, which come from the CSV import file)

const brands = [
  {
    slug: 'nike',
    name: 'Nike',
    category: 'Shoes',
    network: 'CJ Affiliate',
    featured: true,
    description:
      'Performance sportswear and iconic sneakers. Nike runs frequent seasonal markdowns on Air Max, Pegasus and Dri-FIT essentials.',
  },
  {
    slug: 'adidas',
    name: 'Adidas',
    category: 'Shoes',
    network: 'Awin',
    featured: true,
    description:
      'Three-stripe sportswear, Originals sneakers and training gear with regular end-of-season sales.',
  },
  {
    slug: 'zara',
    name: 'Zara',
    category: 'Fashion',
    network: 'Impact',
    featured: true,
    description:
      'Fast-moving runway-inspired collections. Best discounts land during the mid-season and end-of-season sale windows.',
  },
  {
    slug: 'hm',
    name: 'H&M',
    category: 'Fashion',
    network: 'Awin',
    featured: true,
    description:
      'Accessible everyday fashion for women, men and kids with weekly member-only price drops.',
  },
  {
    slug: 'nordstrom',
    name: 'Nordstrom',
    category: 'Fashion',
    network: 'Admitad',
    featured: true,
    description:
      "America's largest fashion marketplace with 4,000+ brands and near-constant coupon activity.",
  },
  {
    slug: 'revolve',
    name: 'Revolve',
    category: 'Fashion',
    network: 'Admitad',
    featured: true,
    description:
      'Curated contemporary and international labels, known for aggressive seasonal markdowns.',
  },
  {
    slug: 'amazon',
    name: 'Amazon Fashion',
    category: 'Shopping',
    network: 'Amazon Associates',
    featured: true,
    description:
      'Everything store with a deep fashion and lifestyle catalogue and lightning deals throughout the day.',
  },
  {
    slug: 'puma',
    name: 'Puma',
    category: 'Shoes',
    network: 'Rakuten Advertising',
    featured: true,
    description:
      'Sport-lifestyle footwear and apparel with strong outlet pricing.',
  },
  {
    slug: 'levis',
    name: "Levi's",
    category: 'Fashion',
    network: 'CJ Affiliate',
    featured: true,
    description:
      'The original denim house. 501s, trucker jackets and western shirts, frequently bundled.',
  },
  {
    slug: 'calvin-klein',
    name: 'Calvin Klein',
    category: 'Fashion',
    network: 'Impact',
    featured: true,
    description:
      'Minimal American design across denim, innerwear and fragrance.',
  },
  {
    slug: 'ulta',
    name: 'Ulta Beauty',
    category: 'Beauty',
    network: 'Admitad',
    description:
      'Beauty and wellness retailer with luxury and mass brands, plus recurring pink-sale events.',
  },
  {
    slug: 'sephora',
    name: 'Sephora',
    category: 'Beauty',
    network: 'Rakuten Advertising',
    description:
      'Prestige beauty destination for makeup, skincare and fragrance.',
  },
  {
    slug: 'bata',
    name: 'Bata',
    category: 'Shoes',
    network: 'Admitad',
    description: 'Everyday footwear for the whole family at value pricing.',
  },
  {
    slug: 'charles-keith',
    name: 'Charles & Keith',
    category: 'Accessories',
    network: 'Impact',
    description:
      'Contemporary bags, footwear and accessories with a strong seasonal sale calendar.',
  },
  {
    slug: 'burberry',
    name: 'Burberry',
    category: 'Luxury',
    network: 'Awin',
    description:
      'British luxury house known for trench coats, check scarves and outerwear.',
  },
  {
    slug: 'armani',
    name: 'Armani',
    category: 'Luxury',
    network: 'Awin',
    description: 'Italian luxury tailoring, watches and fragrance.',
  },
  {
    slug: 'decathlon',
    name: 'Decathlon',
    category: 'Lifestyle',
    network: 'Admitad',
    description:
      'Sports and fitness gear at accessible prices across 60+ in-house brands.',
  },
  {
    slug: 'expedia',
    name: 'Expedia',
    category: 'Travel',
    network: 'Admitad',
    description:
      'Flights, hotels and holiday packages with frequent member-price discounting.',
  },
  {
    slug: 'mango',
    name: 'Mango',
    category: 'Fashion',
    network: 'Impact',
    featured: true,
    description:
      'Mediterranean-inspired womenswear and tailoring with frequent capsule-collection markdowns.',
  },
  {
    slug: 'uniqlo',
    name: 'Uniqlo',
    category: 'Fashion',
    network: 'Awin',
    featured: true,
    description:
      'Japanese basics and technical essentials like Heattech and Airism, often bundled in seasonal sales.',
  },
  {
    slug: 'columbia',
    name: 'Columbia',
    category: 'Lifestyle',
    network: 'CJ Affiliate',
    description:
      'Outdoor and performance wear built for hiking, cold weather and trail use.',
  },
  {
    slug: 'gucci',
    name: 'Gucci',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Italian luxury house spanning ready-to-wear, leather goods and accessories.',
  },
  {
    slug: 'asos',
    name: 'ASOS',
    category: 'Fashion',
    network: 'Impact',
    featured: true,
    description:
      'UK-based fashion marketplace with thousands of third-party and in-house labels.',
  },
  {
    slug: 'shein',
    name: 'SHEIN',
    category: 'Fashion',
    network: 'CJ Affiliate',
    description:
      'Ultra-fast fashion marketplace with thousands of new styles added daily at low prices.',
  },
  {
    slug: 'boohooman',
    name: 'boohooMAN',
    category: 'Fashion',
    network: 'Awin',
    description:
      'Menswear-focused fast fashion with frequent sitewide flash sales.',
  },
  {
    slug: 'prettylittlething',
    name: 'PrettyLittleThing',
    category: 'Fashion',
    network: 'Awin',
    description:
      'Trend-led womenswear known for near-constant promotional pricing.',
  },
  {
    slug: 'forever-21',
    name: 'Forever 21',
    category: 'Fashion',
    network: 'Impact',
    description:
      'Youth-focused fast fashion covering clothing, accessories and beauty.',
  },
  {
    slug: 'gap',
    name: 'Gap',
    category: 'Fashion',
    network: 'CJ Affiliate',
    description:
      'American basics and denim staples with regular seasonal clearance events.',
  },
  {
    slug: 'under-armour',
    name: 'Under Armour',
    category: 'Shoes',
    network: 'CJ Affiliate',
    description:
      'Performance training gear and footwear built around moisture-wicking fabric tech.',
  },
  {
    slug: 'reebok',
    name: 'Reebok',
    category: 'Shoes',
    network: 'Rakuten Advertising',
    description:
      'Training and lifestyle sneakers with a strong CrossFit and retro-runner following.',
  },
  {
    slug: 'new-balance',
    name: 'New Balance',
    category: 'Shoes',
    network: 'CJ Affiliate',
    description:
      'Running-heavy footwear brand known for wide-fit options and collaborator drops.',
  },
  {
    slug: 'lululemon',
    name: 'Lululemon',
    category: 'Fashion',
    network: 'Impact',
    description:
      'Premium yoga and athleisure apparel with limited markdown activity outside outlet drops.',
  },
  {
    slug: 'gymshark',
    name: 'Gymshark',
    category: 'Fashion',
    network: 'Awin',
    description:
      'Direct-to-consumer gymwear brand built on seamless leggings and frequent flash sales.',
  },
  {
    slug: 'the-north-face',
    name: 'The North Face',
    category: 'Lifestyle',
    network: 'CJ Affiliate',
    description:
      'Technical outerwear and outdoor gear for hiking, climbing and cold-weather use.',
  },
  {
    slug: 'ralph-lauren',
    name: 'Ralph Lauren',
    category: 'Fashion',
    network: 'Impact',
    description:
      'American heritage tailoring and polos with recurring seasonal sale events.',
  },
  {
    slug: 'tommy-hilfiger',
    name: 'Tommy Hilfiger',
    category: 'Fashion',
    network: 'Awin',
    description:
      'Preppy American sportswear with denim and outerwear as its strongest categories.',
  },
  {
    slug: 'lacoste',
    name: 'Lacoste',
    category: 'Fashion',
    network: 'Impact',
    description:
      'French sportswear house best known for its polo shirt and tennis heritage.',
  },
  {
    slug: 'hugo-boss',
    name: 'Hugo Boss',
    category: 'Fashion',
    network: 'Awin',
    description:
      'German tailoring and smart-casual menswear, with suiting as its core category.',
  },
  {
    slug: 'michael-kors',
    name: 'Michael Kors',
    category: 'Accessories',
    network: 'Rakuten Advertising',
    description:
      'Accessible luxury handbags, watches and accessories with frequent outlet-style promotions.',
  },
  {
    slug: 'coach',
    name: 'Coach',
    category: 'Accessories',
    network: 'Impact',
    description:
      'American leather goods house known for totes, crossbody bags and outlet pricing.',
  },
  {
    slug: 'kate-spade',
    name: 'Kate Spade',
    category: 'Accessories',
    network: 'Rakuten Advertising',
    description:
      'Colorful handbags and accessories with regular surprise-sale events.',
  },
  {
    slug: 'marc-jacobs',
    name: 'Marc Jacobs',
    category: 'Accessories',
    network: 'Impact',
    description:
      'New York fashion house best known for The Tote Bag and playful ready-to-wear.',
  },
  {
    slug: 'tory-burch',
    name: 'Tory Burch',
    category: 'Accessories',
    network: 'Awin',
    description:
      'American accessories label built around its logo reva flats and structured bags.',
  },
  {
    slug: 'ted-baker',
    name: 'Ted Baker',
    category: 'Accessories',
    network: 'Awin',
    description:
      'British tailoring and accessories with a distinctive floral-print signature.',
  },
  {
    slug: 'fossil',
    name: 'Fossil',
    category: 'Accessories',
    network: 'Rakuten Advertising',
    description:
      'Watches, leather goods and wearables at accessible mid-range pricing.',
  },
  {
    slug: 'longchamp',
    name: 'Longchamp',
    category: 'Accessories',
    network: 'Impact',
    description:
      'French leather goods house famous for its foldable Le Pliage tote.',
  },
  {
    slug: 'prada',
    name: 'Prada',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Italian luxury house spanning ready-to-wear, leather goods and its Linea Rossa sport line.',
  },
  {
    slug: 'versace',
    name: 'Versace',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Italian luxury fashion house known for bold prints and eveningwear.',
  },
  {
    slug: 'balenciaga',
    name: 'Balenciaga',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Avant-garde Parisian luxury house spanning streetwear-inflected ready-to-wear and accessories.',
  },
  {
    slug: 'saint-laurent',
    name: 'Saint Laurent',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Parisian luxury house known for tailored eveningwear and leather goods.',
  },
  {
    slug: 'valentino',
    name: 'Valentino',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Italian couture house recognized for its signature red and eveningwear.',
  },
  {
    slug: 'dolce-gabbana',
    name: 'Dolce & Gabbana',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Italian luxury house spanning tailoring, eveningwear and accessories.',
  },
  {
    slug: 'givenchy',
    name: 'Givenchy',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Parisian luxury house spanning ready-to-wear, leather goods and fragrance.',
  },
  {
    slug: 'moncler',
    name: 'Moncler',
    category: 'Luxury',
    network: 'Awin',
    description:
      'Italian luxury outerwear house best known for down jackets and puffers.',
  },
  {
    slug: 'el-corte-ingles',
    name: 'El Corte Inglés',
    category: 'Shopping',
    network: 'Admitad',
    description:
      "Spain's largest department store chain, spanning fashion, beauty and home.",
  },
  {
    slug: 'primeriti',
    name: 'Primeriti',
    category: 'Shopping',
    network: 'Admitad',
    description:
      'Outlet marketplace for past-season luxury and premium fashion at reduced prices.',
  },
  {
    slug: 'farfetch',
    name: 'FARFETCH',
    category: 'Luxury',
    network: 'Impact',
    description:
      'Global luxury marketplace connecting boutiques and brands from over 50 countries.',
  },
  {
    slug: 'ssense',
    name: 'SSENSE',
    category: 'Luxury',
    network: 'Impact',
    description:
      'Contemporary and luxury multi-brand retailer known for its editorial curation.',
  },
  {
    slug: 'net-a-porter',
    name: 'NET-A-PORTER',
    category: 'Luxury',
    network: 'Admitad',
    description:
      'Luxury womenswear marketplace with same-day delivery in major cities.',
  },
  {
    slug: 'mr-porter',
    name: 'MR PORTER',
    category: 'Luxury',
    network: 'Admitad',
    description:
      'Luxury menswear marketplace and style destination from the Net-a-Porter group.',
  },
  {
    slug: 'mytheresa',
    name: 'Mytheresa',
    category: 'Luxury',
    network: 'Admitad',
    description:
      'German luxury e-commerce platform carrying leading designer ready-to-wear.',
  },
  {
    slug: 'luisaviaroma',
    name: 'Luisaviaroma',
    category: 'Luxury',
    network: 'Admitad',
    description:
      'Florence-based luxury multi-brand retailer with an early-access designer edit.',
  },
  {
    slug: 'selfridges',
    name: 'Selfridges',
    category: 'Shopping',
    network: 'Admitad',
    description:
      'Iconic British department store spanning fashion, beauty and lifestyle.',
  },
  {
    slug: 'harrods',
    name: 'Harrods',
    category: 'Shopping',
    network: 'Admitad',
    description:
      'London luxury department store carrying fashion, beauty and homeware.',
  },
  {
    slug: 'samsonite',
    name: 'Samsonite',
    category: 'Travel',
    network: 'CJ Affiliate',
    description:
      'Hard-case and soft-case luggage brand built for frequent travelers.',
  },
  {
    slug: 'tumi',
    name: 'TUMI',
    category: 'Travel',
    network: 'Admitad',
    description:
      'Premium travel and business bags known for durability and lifetime warranty repairs.',
  },
  {
    slug: 'carters',
    name: "Carter's",
    category: 'Fashion',
    network: 'Awin',
    description:
      "Baby and young children's clothing brand known for everyday basics and sleepwear.",
  },
  {
    slug: 'oshkosh-bgosh',
    name: "OshKosh B'gosh",
    category: 'Fashion',
    network: 'Awin',
    description:
      "Children's overalls and playwear brand with a heritage denim identity.",
  },
  {
    slug: 'the-childrens-place',
    name: "The Children's Place",
    category: 'Fashion',
    network: 'Impact',
    description:
      "Value-priced kids' clothing with frequent storewide percentage-off sales.",
  },
  {
    slug: 'gap-kids',
    name: 'GAP Kids',
    category: 'Fashion',
    network: 'CJ Affiliate',
    description:
      "Gap's children's line, covering basics, denim and outerwear for kids.",
  },
  {
    slug: 'hm-kids',
    name: 'H&M Kids',
    category: 'Fashion',
    network: 'Awin',
    description:
      "H&M's children's line spanning everyday basics to occasionwear.",
  },
  {
    slug: 'jordan',
    name: 'Jordan',
    category: 'Shoes',
    network: 'CJ Affiliate',
    description:
      "Nike's basketball-heritage brand built around the Air Jordan retro lineup.",
  },
  {
    slug: 'asos-design',
    name: 'ASOS DESIGN',
    category: 'Fashion',
    network: 'Impact',
    description:
      "ASOS's in-house label spanning everyday and occasion fashion.",
  },
  {
    slug: 'adidas-originals',
    name: 'Adidas Originals',
    category: 'Shoes',
    network: 'Awin',
    description:
      "Adidas's heritage lifestyle line, home to the Samba, Gazelle and Campus families.",
  },
]

const stores = [
  {
    slug: 'nordstrom',
    name: 'Nordstrom',
    domain: 'nordstrom.com',
    network: 'Admitad',
    campaign: 'dc-nordstrom',
    storeId: 'ST-101',
    subId: 'home',
    shipsTo: 'US',
    storeWideOffer: 'Extra 10% off with STYLE10',
    featured: true,
    description:
      "America's largest multi-brand fashion marketplace, with 4,000+ labels across clothing, footwear, beauty and accessories.",
  },
  {
    slug: 'revolve',
    name: 'Revolve',
    domain: 'revolve.com',
    network: 'Admitad',
    campaign: 'dc-revolve',
    storeId: 'ST-102',
    subId: 'home',
    shipsTo: 'US',
    storeWideOffer: 'Up to 25% extra off sale styles',
    featured: true,
    description:
      'Contemporary fashion destination known for curated labels, a Luxe edit and aggressive seasonal markdowns.',
  },
  {
    slug: 'nike-store',
    name: 'Nike.com',
    domain: 'nike.com',
    network: 'CJ Affiliate',
    campaign: 'dc-nike',
    storeId: 'ST-103',
    subId: 'home',
    shipsTo: 'US, Global',
    storeWideOffer: 'Free shipping for members',
    featured: true,
    description:
      'The official Nike store — first access to new silhouettes and member-only pricing.',
  },
  {
    slug: 'adidas-store',
    name: 'Adidas.com',
    domain: 'adidas.com',
    network: 'Awin',
    campaign: 'dc-adidas',
    storeId: 'ST-104',
    subId: 'home',
    shipsTo: 'US, Global',
    featured: true,
    description:
      'Official Adidas store with Originals, Performance and end-of-season clearance.',
  },
  {
    slug: 'amazon',
    name: 'Amazon Fashion',
    domain: 'amazon.com',
    network: 'Amazon Associates',
    campaign: 'dc-amazon',
    storeId: 'ST-105',
    subId: 'home',
    shipsTo: 'US',
    storeWideOffer: 'Lightning deals refreshed hourly',
    featured: true,
    description:
      'Deep fashion and lifestyle catalogue with fast delivery and continuous lightning deals.',
  },
  {
    slug: 'neiman-marcus',
    name: 'Neiman Marcus',
    domain: 'neimanmarcus.com',
    network: 'Impact',
    campaign: 'dc-neimanmarcus',
    storeId: 'ST-106',
    subId: 'home',
    shipsTo: 'US',
    featured: true,
    sponsored: true,
    description:
      'Authenticated luxury and premium fashion, watches and beauty from American and global houses.',
  },
  {
    slug: 'rei',
    name: 'REI',
    domain: 'rei.com',
    network: 'Admitad',
    campaign: 'dc-rei',
    storeId: 'ST-260',
    subId: 'home',
    shipsTo: 'US',
    description:
      'Outdoor specialty retailer stocking Columbia, The North Face and other trail and camp brands.',
  },
  {
    slug: 'nordstrom-rack',
    name: 'Nordstrom Rack',
    domain: 'nordstromrack.com',
    network: 'Admitad',
    campaign: 'dc-nordstrom-rack',
    storeId: 'ST-261',
    subId: 'home',
    shipsTo: 'US',
    storeWideOffer: 'Off-price designer and premium brands',
    description:
      "Nordstrom's off-price outlet carrying discounted designer and premium-brand apparel and footwear.",
  },
  {
    slug: 'footlocker',
    name: 'Foot Locker',
    domain: 'footlocker.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-footlocker',
    storeId: 'ST-107',
    subId: 'home',
    shipsTo: 'Global',
    description:
      'Sneaker specialist stocking Nike, Adidas, Puma and New Balance releases.',
  },
  {
    slug: 'ulta',
    name: 'Ulta Beauty',
    domain: 'ulta.com',
    network: 'Admitad',
    campaign: 'dc-ulta',
    storeId: 'ST-108',
    subId: 'home',
    shipsTo: 'US',
    storeWideOffer: 'Beauty bundles from $9',
    description:
      'Beauty and wellness retailer carrying prestige, K-beauty and mass brands.',
  },
  {
    slug: 'zara-store',
    name: 'Zara',
    domain: 'zara.com',
    network: 'Impact',
    campaign: 'dc-zara',
    storeId: 'ST-109',
    subId: 'home',
    shipsTo: 'US, Global',
    description:
      'Runway-led collections refreshed twice weekly, with two big sale windows a year.',
  },
  {
    slug: 'hm-store',
    name: 'H&M',
    domain: 'hm.com',
    network: 'Awin',
    campaign: 'dc-hm',
    storeId: 'ST-110',
    subId: 'home',
    shipsTo: 'US, Global',
    description:
      'Everyday fashion for women, men and kids plus a growing home line.',
  },
  {
    slug: 'decathlon',
    name: 'Decathlon',
    domain: 'decathlon.com',
    network: 'Admitad',
    campaign: 'dc-decathlon',
    storeId: 'ST-111',
    subId: 'home',
    shipsTo: 'US',
    description:
      'Sports, fitness and outdoor gear at accessible pricing across 60+ in-house brands.',
  },
  {
    slug: 'sephora',
    name: 'Sephora',
    domain: 'sephora.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-sephora',
    storeId: 'ST-112',
    subId: 'home',
    shipsTo: 'US',
    description:
      'Prestige beauty destination for makeup, skincare and fragrance.',
  },
  {
    slug: 'mango-store',
    name: 'Mango',
    domain: 'mango.com',
    network: 'Impact',
    campaign: 'dc-mango',
    storeId: 'ST-113',
    subId: 'home',
    shipsTo: 'US, Global',
    description:
      'Mediterranean-inspired womenswear and tailoring with regular capsule-collection markdowns.',
  },
  {
    slug: 'uniqlo-store',
    name: 'Uniqlo',
    domain: 'uniqlo.com',
    network: 'Awin',
    campaign: 'dc-uniqlo',
    storeId: 'ST-114',
    subId: 'home',
    shipsTo: 'US, Global',
    storeWideOffer: 'Extra 10% off Heattech and Airism',
    description:
      'Japanese basics and technical essentials, refreshed seasonally with member-only pricing.',
  },
  {
    slug: 'columbia-store',
    name: 'Columbia',
    domain: 'columbia.com',
    network: 'CJ Affiliate',
    campaign: 'dc-columbia',
    storeId: 'ST-115',
    subId: 'home',
    shipsTo: 'US, Global',
    description:
      'Outdoor and performance wear for hiking, cold weather and trail use.',
  },
  {
    slug: 'asos-store',
    name: 'ASOS',
    domain: 'asos.com',
    network: 'Impact',
    campaign: 'dc-asos',
    storeId: 'ST-116',
    subId: 'home',
    shipsTo: 'US, Global',
    featured: true,
    description:
      'UK-based fashion marketplace with thousands of third-party and in-house labels.',
  },
  {
    slug: 'puma-store',
    name: 'Puma',
    domain: 'puma.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-puma-store',
    storeId: 'ST-200',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Puma.',
  },
  {
    slug: 'levis-store',
    name: 'Levis',
    domain: 'levi.com',
    network: 'CJ Affiliate',
    campaign: 'dc-levis-store',
    storeId: 'ST-201',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Levis.',
  },
  {
    slug: 'calvin-klein-store',
    name: 'Calvin Klein',
    domain: 'calvinklein.com',
    network: 'Impact',
    campaign: 'dc-calvin-klein-store',
    storeId: 'ST-202',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Calvin Klein.',
  },
  {
    slug: 'bata-store',
    name: 'Bata',
    domain: 'bata.com',
    network: 'Admitad',
    campaign: 'dc-bata-store',
    storeId: 'ST-203',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Bata.',
  },
  {
    slug: 'charles-keith-store',
    name: 'Charles Keith',
    domain: 'charleskeith.com',
    network: 'Impact',
    campaign: 'dc-charles-keith-store',
    storeId: 'ST-204',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Charles Keith.',
  },
  {
    slug: 'burberry-store',
    name: 'Burberry',
    domain: 'burberry.com',
    network: 'Awin',
    campaign: 'dc-burberry-store',
    storeId: 'ST-205',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Burberry.',
  },
  {
    slug: 'armani-store',
    name: 'Armani',
    domain: 'armani.com',
    network: 'Awin',
    campaign: 'dc-armani-store',
    storeId: 'ST-206',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Armani.',
  },
  {
    slug: 'expedia-store',
    name: 'Expedia',
    domain: 'expedia.com',
    network: 'Admitad',
    campaign: 'dc-expedia-store',
    storeId: 'ST-207',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Expedia.',
  },
  {
    slug: 'gucci-store',
    name: 'Gucci',
    domain: 'gucci.com',
    network: 'Awin',
    campaign: 'dc-gucci-store',
    storeId: 'ST-208',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Gucci.',
  },
  {
    slug: 'shein-store',
    name: 'Shein',
    domain: 'shein.com',
    network: 'CJ Affiliate',
    campaign: 'dc-shein-store',
    storeId: 'ST-209',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Shein.',
  },
  {
    slug: 'boohooman-store',
    name: 'Boohooman',
    domain: 'boohooman.com',
    network: 'Awin',
    campaign: 'dc-boohooman-store',
    storeId: 'ST-210',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Boohooman.',
  },
  {
    slug: 'prettylittlething-store',
    name: 'Prettylittlething',
    domain: 'prettylittlething.com',
    network: 'Awin',
    campaign: 'dc-prettylittlething-store',
    storeId: 'ST-211',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Prettylittlething.',
  },
  {
    slug: 'forever-21-store',
    name: 'Forever 21',
    domain: 'forever21.com',
    network: 'Impact',
    campaign: 'dc-forever-21-store',
    storeId: 'ST-212',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Forever 21.',
  },
  {
    slug: 'gap-store',
    name: 'Gap',
    domain: 'gap.com',
    network: 'CJ Affiliate',
    campaign: 'dc-gap-store',
    storeId: 'ST-213',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Gap.',
  },
  {
    slug: 'under-armour-store',
    name: 'Under Armour',
    domain: 'underarmour.com',
    network: 'CJ Affiliate',
    campaign: 'dc-under-armour-store',
    storeId: 'ST-214',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Under Armour.',
  },
  {
    slug: 'reebok-store',
    name: 'Reebok',
    domain: 'reebok.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-reebok-store',
    storeId: 'ST-215',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Reebok.',
  },
  {
    slug: 'new-balance-store',
    name: 'New Balance',
    domain: 'newbalance.com',
    network: 'CJ Affiliate',
    campaign: 'dc-new-balance-store',
    storeId: 'ST-216',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for New Balance.',
  },
  {
    slug: 'lululemon-store',
    name: 'Lululemon',
    domain: 'lululemon.com',
    network: 'Impact',
    campaign: 'dc-lululemon-store',
    storeId: 'ST-217',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Lululemon.',
  },
  {
    slug: 'gymshark-store',
    name: 'Gymshark',
    domain: 'gymshark.com',
    network: 'Awin',
    campaign: 'dc-gymshark-store',
    storeId: 'ST-218',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Gymshark.',
  },
  {
    slug: 'the-north-face-store',
    name: 'The North Face',
    domain: 'thenorthface.com',
    network: 'CJ Affiliate',
    campaign: 'dc-the-north-face-store',
    storeId: 'ST-219',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for The North Face.',
  },
  {
    slug: 'ralph-lauren-store',
    name: 'Ralph Lauren',
    domain: 'ralphlauren.com',
    network: 'Impact',
    campaign: 'dc-ralph-lauren-store',
    storeId: 'ST-220',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Ralph Lauren.',
  },
  {
    slug: 'tommy-hilfiger-store',
    name: 'Tommy Hilfiger',
    domain: 'usa.tommy.com',
    network: 'Awin',
    campaign: 'dc-tommy-hilfiger-store',
    storeId: 'ST-221',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Tommy Hilfiger.',
  },
  {
    slug: 'lacoste-store',
    name: 'Lacoste',
    domain: 'lacoste.com',
    network: 'Impact',
    campaign: 'dc-lacoste-store',
    storeId: 'ST-222',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Lacoste.',
  },
  {
    slug: 'hugo-boss-store',
    name: 'Hugo Boss',
    domain: 'hugoboss.com',
    network: 'Awin',
    campaign: 'dc-hugo-boss-store',
    storeId: 'ST-223',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Hugo Boss.',
  },
  {
    slug: 'michael-kors-store',
    name: 'Michael Kors',
    domain: 'michaelkors.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-michael-kors-store',
    storeId: 'ST-224',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Michael Kors.',
  },
  {
    slug: 'coach-store',
    name: 'Coach',
    domain: 'coach.com',
    network: 'Impact',
    campaign: 'dc-coach-store',
    storeId: 'ST-225',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Coach.',
  },
  {
    slug: 'kate-spade-store',
    name: 'Kate Spade',
    domain: 'katespade.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-kate-spade-store',
    storeId: 'ST-226',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Kate Spade.',
  },
  {
    slug: 'marc-jacobs-store',
    name: 'Marc Jacobs',
    domain: 'marcjacobs.com',
    network: 'Impact',
    campaign: 'dc-marc-jacobs-store',
    storeId: 'ST-227',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Marc Jacobs.',
  },
  {
    slug: 'tory-burch-store',
    name: 'Tory Burch',
    domain: 'toryburch.com',
    network: 'Awin',
    campaign: 'dc-tory-burch-store',
    storeId: 'ST-228',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Tory Burch.',
  },
  {
    slug: 'ted-baker-store',
    name: 'Ted Baker',
    domain: 'tedbaker.com',
    network: 'Awin',
    campaign: 'dc-ted-baker-store',
    storeId: 'ST-229',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Ted Baker.',
  },
  {
    slug: 'fossil-store',
    name: 'Fossil',
    domain: 'fossil.com',
    network: 'Rakuten Advertising',
    campaign: 'dc-fossil-store',
    storeId: 'ST-230',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Fossil.',
  },
  {
    slug: 'longchamp-store',
    name: 'Longchamp',
    domain: 'longchamp.com',
    network: 'Impact',
    campaign: 'dc-longchamp-store',
    storeId: 'ST-231',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Longchamp.',
  },
  {
    slug: 'prada-store',
    name: 'Prada',
    domain: 'prada.com',
    network: 'Awin',
    campaign: 'dc-prada-store',
    storeId: 'ST-232',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Prada.',
  },
  {
    slug: 'versace-store',
    name: 'Versace',
    domain: 'versace.com',
    network: 'Awin',
    campaign: 'dc-versace-store',
    storeId: 'ST-233',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Versace.',
  },
  {
    slug: 'balenciaga-store',
    name: 'Balenciaga',
    domain: 'balenciaga.com',
    network: 'Awin',
    campaign: 'dc-balenciaga-store',
    storeId: 'ST-234',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Balenciaga.',
  },
  {
    slug: 'saint-laurent-store',
    name: 'Saint Laurent',
    domain: 'ysl.com',
    network: 'Awin',
    campaign: 'dc-saint-laurent-store',
    storeId: 'ST-235',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Saint Laurent.',
  },
  {
    slug: 'valentino-store',
    name: 'Valentino',
    domain: 'valentino.com',
    network: 'Awin',
    campaign: 'dc-valentino-store',
    storeId: 'ST-236',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Valentino.',
  },
  {
    slug: 'dolce-gabbana-store',
    name: 'Dolce Gabbana',
    domain: 'dolcegabbana.com',
    network: 'Awin',
    campaign: 'dc-dolce-gabbana-store',
    storeId: 'ST-237',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Dolce Gabbana.',
  },
  {
    slug: 'givenchy-store',
    name: 'Givenchy',
    domain: 'givenchy.com',
    network: 'Awin',
    campaign: 'dc-givenchy-store',
    storeId: 'ST-238',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Givenchy.',
  },
  {
    slug: 'moncler-store',
    name: 'Moncler',
    domain: 'moncler.com',
    network: 'Awin',
    campaign: 'dc-moncler-store',
    storeId: 'ST-239',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Moncler.',
  },
  {
    slug: 'el-corte-ingles-store',
    name: 'El Corte Ingles',
    domain: 'elcorteingles.es',
    network: 'Admitad',
    campaign: 'dc-el-corte-ingles-store',
    storeId: 'ST-240',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for El Corte Ingles.',
  },
  {
    slug: 'primeriti-store',
    name: 'Primeriti',
    domain: 'primeriti.es',
    network: 'Admitad',
    campaign: 'dc-primeriti-store',
    storeId: 'ST-241',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Primeriti.',
  },
  {
    slug: 'farfetch-store',
    name: 'Farfetch',
    domain: 'farfetch.com',
    network: 'Impact',
    campaign: 'dc-farfetch-store',
    storeId: 'ST-242',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Farfetch.',
  },
  {
    slug: 'ssense-store',
    name: 'Ssense',
    domain: 'ssense.com',
    network: 'Impact',
    campaign: 'dc-ssense-store',
    storeId: 'ST-243',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Ssense.',
  },
  {
    slug: 'net-a-porter-store',
    name: 'Net A Porter',
    domain: 'net-a-porter.com',
    network: 'Admitad',
    campaign: 'dc-net-a-porter-store',
    storeId: 'ST-244',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Net A Porter.',
  },
  {
    slug: 'mr-porter-store',
    name: 'Mr Porter',
    domain: 'mrporter.com',
    network: 'Admitad',
    campaign: 'dc-mr-porter-store',
    storeId: 'ST-245',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Mr Porter.',
  },
  {
    slug: 'mytheresa-store',
    name: 'Mytheresa',
    domain: 'mytheresa.com',
    network: 'Admitad',
    campaign: 'dc-mytheresa-store',
    storeId: 'ST-246',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Mytheresa.',
  },
  {
    slug: 'luisaviaroma-store',
    name: 'Luisaviaroma',
    domain: 'luisaviaroma.com',
    network: 'Admitad',
    campaign: 'dc-luisaviaroma-store',
    storeId: 'ST-247',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Luisaviaroma.',
  },
  {
    slug: 'selfridges-store',
    name: 'Selfridges',
    domain: 'selfridges.com',
    network: 'Admitad',
    campaign: 'dc-selfridges-store',
    storeId: 'ST-248',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Selfridges.',
  },
  {
    slug: 'harrods-store',
    name: 'Harrods',
    domain: 'harrods.com',
    network: 'Admitad',
    campaign: 'dc-harrods-store',
    storeId: 'ST-249',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Harrods.',
  },
  {
    slug: 'samsonite-store',
    name: 'Samsonite',
    domain: 'samsonite.com',
    network: 'CJ Affiliate',
    campaign: 'dc-samsonite-store',
    storeId: 'ST-250',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Samsonite.',
  },
  {
    slug: 'tumi-store',
    name: 'Tumi',
    domain: 'tumi.com',
    network: 'Admitad',
    campaign: 'dc-tumi-store',
    storeId: 'ST-251',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Tumi.',
  },
  {
    slug: 'carters-store',
    name: 'Carters',
    domain: 'carters.com',
    network: 'Awin',
    campaign: 'dc-carters-store',
    storeId: 'ST-252',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Carters.',
  },
  {
    slug: 'oshkosh-bgosh-store',
    name: 'Oshkosh Bgosh',
    domain: 'oshkosh.com',
    network: 'Awin',
    campaign: 'dc-oshkosh-bgosh-store',
    storeId: 'ST-253',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Oshkosh Bgosh.',
  },
  {
    slug: 'the-childrens-place-store',
    name: 'The Childrens Place',
    domain: 'childrensplace.com',
    network: 'Impact',
    campaign: 'dc-the-childrens-place-store',
    storeId: 'ST-254',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for The Childrens Place.',
  },
  {
    slug: 'gap-kids-store',
    name: 'Gap Kids',
    domain: 'gap.com',
    network: 'CJ Affiliate',
    campaign: 'dc-gap-kids-store',
    storeId: 'ST-255',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Gap Kids.',
  },
  {
    slug: 'hm-kids-store',
    name: 'Hm Kids',
    domain: 'hm.com',
    network: 'Awin',
    campaign: 'dc-hm-kids-store',
    storeId: 'ST-256',
    subId: 'home',
    shipsTo: 'Global',
    description: 'Official/partner listings for Hm Kids.',
  },
]

// getBrand helper (mirrors catalog.ts)
const brandBySlug = new Map(brands.map((b) => [b.slug, b]))
const getBrand = (slug) => brandBySlug.get(slug)
const brandName = (slug) => getBrand(slug)?.name ?? slug

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/[₹%,]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

// Raw deal seeds — copied verbatim from catalog.ts `seeds` array
const dealSeeds = [
  {
    t: 'Nike Air Max Sneakers at 35% Off',
    p: 'Air Max 270 Sneakers',
    b: 'nike',
    c: 'shoes',
    sub: 'Sneakers',
    op: 12999,
    np: 8499,
    code: 'NIKE35',
    type: 'Coupon Deal',
    badges: ['HOT DEAL', 'COUPON'],
    h: 46,
    tags: ['sneakers', 'nike', 'under-10000'],
    featured: true,
    clicks: 4821,
  },
  {
    t: 'Zara Summer Collection Flat 40% Off',
    p: 'Summer Linen Collection',
    b: 'zara',
    c: 'fashion',
    sub: "Women's Fashion",
    op: 4999,
    np: 2999,
    code: 'SUMMER40',
    type: 'Seasonal Sale',
    badges: ["EDITOR'S PICK", 'COUPON'],
    h: 48,
    tags: ['summer', 'linen', 'women'],
    featured: true,
    clicks: 3910,
  },
  {
    t: 'Adidas Ultraboost Light Running Shoes',
    p: 'Ultraboost Light',
    b: 'adidas',
    c: 'shoes',
    sub: 'Running',
    op: 18999,
    np: 11399,
    type: 'Store Sale',
    badges: ['BEST PRICE'],
    h: 120,
    tags: ['running', 'sneakers'],
    featured: true,
    clicks: 2984,
  },
  {
    t: 'Nordstrom End of Reason Sale — Up to 80% Off',
    p: 'End of Reason Sale',
    b: 'nordstrom',
    c: 'fashion',
    op: 3999,
    np: 999,
    code: 'STYLE20',
    type: 'Mega Sale',
    badges: ['HOT DEAL', 'LIMITED TIME'],
    h: 71,
    tags: ['sale', 'marketplace'],
    featured: true,
    clicks: 7211,
  },
  {
    t: 'Revolve Big Bold Sale — Extra 25% Off',
    p: 'Big Bold Sale',
    b: 'revolve',
    c: 'fashion',
    op: 2499,
    np: 1499,
    code: 'REVOLVE25',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 30,
    tags: ['sale', 'extra-off'],
    clicks: 5120,
  },
  {
    t: 'H&M Basics Bundle — Buy 2 Get 1',
    p: 'Cotton Basics Bundle',
    b: 'hm',
    c: 'fashion',
    sub: "Men's Fashion",
    op: 2097,
    np: 1398,
    type: 'Bundle Offer',
    badges: ['BEST PRICE'],
    h: 96,
    tags: ['basics', 'bundle', 'men'],
    clicks: 1877,
  },
  {
    t: "Levi's 501 Original Jeans at 45% Off",
    p: '501 Original Fit Jeans',
    b: 'levis',
    c: 'fashion',
    sub: "Men's Fashion",
    op: 4999,
    np: 2749,
    code: 'DENIM45',
    type: 'Coupon Deal',
    badges: ['HOT DEAL', 'COUPON'],
    h: 18,
    tags: ['denim', 'jeans', 'men'],
    flash: true,
    clicks: 3320,
  },
  {
    t: 'Puma Flash Sale — Extra 30% Off Sale Styles',
    p: 'Sale Styles',
    b: 'puma',
    c: 'shoes',
    sub: 'Sneakers',
    op: 5999,
    np: 3499,
    code: 'PUMA30',
    type: 'Flash Sale',
    badges: ['FLASH SALE', 'LIMITED TIME'],
    h: 8,
    tags: ['flash', 'sneakers'],
    flash: true,
    clicks: 2610,
  },
  {
    t: 'Calvin Klein Fragrance Gift Set 30% Off',
    p: 'CK One Gift Set',
    b: 'calvin-klein',
    c: 'beauty',
    sub: 'Fragrances',
    op: 6499,
    np: 4549,
    type: 'Store Sale',
    badges: ['EXCLUSIVE'],
    h: 60,
    tags: ['fragrance', 'gifting'],
    clicks: 1420,
  },
  {
    t: 'Ulta Pink Friday Sale — Up to 50% Off Beauty',
    p: 'Pink Friday Sale',
    b: 'ulta',
    c: 'beauty',
    sub: 'Makeup',
    op: 1999,
    np: 999,
    code: 'PINK50',
    type: 'Seasonal Sale',
    badges: ['HOT DEAL', 'COUPON'],
    h: 40,
    tags: ['beauty', 'makeup'],
    featured: true,
    clicks: 4102,
  },
  {
    t: 'Sephora Skincare Sets at 25% Off',
    p: 'Luxury Skincare Set',
    b: 'sephora',
    c: 'beauty',
    sub: 'Skincare',
    op: 8999,
    np: 6749,
    code: 'GLOW25',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 90,
    tags: ['skincare', 'luxury'],
    clicks: 1290,
  },
  {
    t: 'Charles & Keith Handbags — Flat 40% Off',
    p: 'Structured Tote Bag',
    b: 'charles-keith',
    c: 'accessories',
    sub: 'Bags',
    op: 7999,
    np: 4799,
    type: 'Seasonal Sale',
    badges: ["EDITOR'S PICK"],
    h: 52,
    tags: ['bags', 'women'],
    featured: true,
    clicks: 2211,
  },
  {
    t: 'Armani Exchange Watches Up to 45% Off',
    p: 'AX Chronograph Watch',
    b: 'armani',
    c: 'accessories',
    sub: 'Watches',
    op: 21999,
    np: 12099,
    type: 'Clearance',
    badges: ['BEST PRICE'],
    h: 200,
    tags: ['watches', 'luxury'],
    clicks: 980,
  },
  {
    t: 'Burberry Check Scarf — Members Only Price',
    p: 'Classic Check Cashmere Scarf',
    b: 'burberry',
    c: 'accessories',
    op: 42000,
    np: 33600,
    type: 'Exclusive Offer',
    badges: ['EXCLUSIVE', 'LIMITED TIME'],
    h: 26,
    tags: ['luxury', 'scarf'],
    clicks: 640,
  },
  {
    t: 'Bata Formal Shoes Starting $16',
    p: 'Leather Derby Shoes',
    b: 'bata',
    c: 'shoes',
    sub: 'Formal',
    op: 2599,
    np: 1299,
    code: 'BATA50',
    type: 'Coupon Deal',
    badges: ['COUPON', 'BEST PRICE'],
    h: 110,
    tags: ['formal', 'men', 'under-3000'],
    clicks: 1560,
  },
  {
    t: 'Decathlon Fitness Gear — Flat 30% Off',
    p: 'Home Gym Essentials',
    b: 'decathlon',
    c: 'lifestyle',
    sub: 'Fitness',
    op: 4499,
    np: 3149,
    type: 'Store Sale',
    badges: ['BEST PRICE'],
    h: 140,
    tags: ['fitness', 'home'],
    clicks: 1105,
  },
  {
    t: 'Expedia Hotel Bookings — Extra 20% Off',
    p: 'US Hotel Bookings',
    b: 'expedia',
    c: 'travel',
    sub: 'Hotels',
    op: 10000,
    np: 8000,
    code: 'STAY20',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 300,
    tags: ['travel', 'hotels'],
    clicks: 2044,
  },
  {
    t: 'Amazon Lightning Deal — Fashion Under $12',
    p: 'Fashion Under $12 Store',
    b: 'amazon',
    c: 'fashion',
    op: 1999,
    np: 899,
    type: 'Flash Sale',
    badges: ['FLASH SALE'],
    h: 5,
    tags: ['flash', 'budget'],
    flash: true,
    clicks: 6033,
  },
  {
    t: 'Nike Dri-FIT Training Tees — 2 for $36',
    p: 'Dri-FIT Training Tee',
    b: 'nike',
    c: 'fashion',
    sub: "Men's Fashion",
    op: 4598,
    np: 2999,
    type: 'Bundle Offer',
    badges: ['BEST PRICE'],
    h: 72,
    tags: ['activewear', 'men'],
    clicks: 1732,
  },
  {
    t: 'Adidas Originals Track Jacket 50% Off',
    p: 'Firebird Track Jacket',
    b: 'adidas',
    c: 'fashion',
    sub: 'Streetwear',
    op: 5999,
    np: 2999,
    code: 'TRACK50',
    type: 'Coupon Deal',
    badges: ['COUPON', 'HOT DEAL'],
    h: 22,
    tags: ['streetwear', 'jacket'],
    flash: true,
    clicks: 2870,
  },
  {
    t: 'Zara Kids Autumn Edit — Up to 60% Off',
    p: 'Kids Autumn Edit',
    b: 'zara',
    c: 'fashion',
    sub: 'Kids',
    op: 2999,
    np: 1199,
    type: 'Seasonal Sale',
    badges: ['LIMITED TIME'],
    h: 84,
    tags: ['kids', 'autumn'],
    clicks: 890,
  },
  {
    t: 'H&M Home Textiles — Flat 35% Off',
    p: 'Linen Bedding Set',
    b: 'hm',
    c: 'lifestyle',
    sub: 'Home',
    op: 4999,
    np: 3249,
    type: 'Store Sale',
    badges: ["EDITOR'S PICK"],
    h: 130,
    tags: ['home', 'bedding'],
    clicks: 710,
  },
  {
    t: 'Nordstrom Beauty Fest — Buy 2 Get 2 Free',
    p: 'Beauty Fest',
    b: 'nordstrom',
    c: 'beauty',
    sub: 'Makeup',
    op: 2400,
    np: 1200,
    code: 'BEAUTY4',
    type: 'Bundle Offer',
    badges: ['COUPON'],
    h: 44,
    tags: ['beauty', 'bogo'],
    clicks: 1980,
  },
  {
    t: 'Revolve Luxe — Designer Labels Up to 65% Off',
    p: 'Revolve Luxe Edit',
    b: 'revolve',
    c: 'fashion',
    sub: 'Luxury Fashion',
    op: 15999,
    np: 5599,
    type: 'Clearance',
    badges: ["EDITOR'S PICK"],
    h: 160,
    tags: ['luxury', 'designer'],
    clicks: 1340,
  },
  {
    t: 'Puma Running Shoes Under $36',
    p: 'Softride Running Shoes',
    b: 'puma',
    c: 'shoes',
    sub: 'Running',
    op: 4999,
    np: 2799,
    type: 'Store Sale',
    badges: ['BEST PRICE'],
    h: 210,
    tags: ['running', 'under-3000'],
    clicks: 2450,
  },
  {
    t: "Levi's Trucker Jacket — Extra 25% Off",
    p: 'Sherpa Trucker Jacket',
    b: 'levis',
    c: 'fashion',
    sub: 'Streetwear',
    op: 7999,
    np: 5999,
    code: 'TRUCK25',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 66,
    tags: ['denim', 'jacket'],
    clicks: 1120,
  },
  {
    t: 'Sephora Fragrance Week — 20% Off Sitewide',
    p: 'Fragrance Week',
    b: 'sephora',
    c: 'beauty',
    sub: 'Fragrances',
    op: 5999,
    np: 4799,
    code: 'SCENT20',
    type: 'Seasonal Sale',
    badges: ['COUPON', 'LIMITED TIME'],
    h: 12,
    tags: ['fragrance'],
    flash: true,
    clicks: 1610,
  },
  {
    t: 'Ulta Haircare Bundles — Flat 40% Off',
    p: 'Haircare Repair Bundle',
    b: 'ulta',
    c: 'beauty',
    sub: 'Haircare',
    op: 2499,
    np: 1499,
    type: 'Bundle Offer',
    badges: ['BEST PRICE'],
    h: 100,
    tags: ['haircare'],
    clicks: 930,
  },
  {
    t: 'Charles & Keith Sale Footwear Extra 20% Off',
    p: 'Sale Heels & Loafers',
    b: 'charles-keith',
    c: 'shoes',
    sub: 'Heels',
    op: 5499,
    np: 3299,
    code: 'CK20',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 34,
    tags: ['heels', 'women'],
    clicks: 1044,
  },
  {
    t: 'Decathlon Travel Backpacks From $18',
    p: '40L Travel Backpack',
    b: 'decathlon',
    c: 'travel',
    sub: 'Luggage',
    op: 2999,
    np: 1499,
    type: 'Store Sale',
    badges: ['BEST PRICE'],
    h: 190,
    tags: ['travel', 'luggage'],
    clicks: 860,
  },
  {
    t: 'Amazon Fashion Festival — Partner Offer',
    p: 'Fashion Festival Store',
    b: 'amazon',
    c: 'fashion',
    op: 4999,
    np: 2499,
    type: 'Sponsored',
    badges: ['SPONSORED', 'HOT DEAL'],
    h: 58,
    tags: ['festival', 'sale'],
    sponsored: true,
    featured: true,
    clicks: 5309,
  },
  {
    t: 'Expedia Flight Sale — Flat $18 Off',
    p: 'US Domestic Flights',
    b: 'expedia',
    c: 'travel',
    sub: 'Flights',
    op: 6500,
    np: 5000,
    code: 'FLY1500',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 250,
    tags: ['flights', 'travel'],
    clicks: 1780,
  },
  {
    t: 'Nike Pegasus 40 — Holiday Sale Price',
    p: 'Pegasus 40',
    b: 'nike',
    c: 'shoes',
    sub: 'Running',
    op: 11999,
    np: 7799,
    type: 'Holiday Offer',
    badges: ['LIMITED TIME'],
    h: -20,
    status: 'EXPIRED',
    tags: ['running', 'holiday'],
    clicks: 3311,
  },
  {
    t: 'Zara Winter Coats — Early Access',
    p: 'Wool Blend Coat',
    b: 'zara',
    c: 'fashion',
    sub: "Women's Fashion",
    op: 9999,
    np: 6999,
    type: 'Upcoming Sale',
    badges: ['EXCLUSIVE'],
    h: 400,
    status: 'UPCOMING',
    tags: ['winter', 'coats'],
    clicks: 210,
  },
  {
    t: 'Burberry Trench Coat Archive Sale',
    p: 'Kensington Trench Coat',
    b: 'burberry',
    c: 'fashion',
    sub: 'Luxury Fashion',
    op: 185000,
    np: 129500,
    type: 'Clearance',
    badges: ['EXCLUSIVE'],
    h: -60,
    status: 'EXPIRED',
    tags: ['luxury', 'outerwear'],
    clicks: 540,
  },
  {
    t: 'Mango Tailored Blazers — Up to 30% Off',
    p: 'Structured Blazer Dress',
    b: 'mango',
    c: 'fashion',
    sub: "Women's Fashion",
    op: 5999,
    np: 4199,
    code: 'MANGO30',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 50,
    tags: ['dresses', 'women'],
    featured: true,
    clicks: 1500,
  },
  {
    t: 'Uniqlo Airism Basics — Buy 3 Save More',
    p: 'Airism Crew Neck Tee 3-Pack',
    b: 'uniqlo',
    c: 'fashion',
    sub: "Men's Fashion",
    op: 2490,
    np: 1990,
    type: 'Bundle Offer',
    badges: ['BEST PRICE'],
    h: 80,
    tags: ['basics', 'bundle'],
    clicks: 1200,
  },
  {
    t: 'Columbia Outdoor Jackets — Flat 25% Off',
    p: 'Ridge Plate Fleece Jacket',
    b: 'columbia',
    c: 'fashion',
    sub: "Men's Fashion",
    op: 6999,
    np: 5249,
    code: 'TRAIL25',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 65,
    tags: ['outdoor', 'jacket'],
    clicks: 800,
  },
  {
    t: 'Gucci Ace Sneakers — Exclusive Members Price',
    p: 'Ace Leather Sneakers',
    b: 'gucci',
    c: 'shoes',
    sub: 'Sneakers',
    op: 62000,
    np: 52700,
    type: 'Exclusive Offer',
    badges: ['EXCLUSIVE'],
    h: 40,
    tags: ['luxury', 'sneakers'],
    clicks: 430,
  },
  {
    t: 'ASOS Design Edit — Extra 20% Off',
    p: 'Asos Design Wrap Midi Dress',
    b: 'asos',
    c: 'fashion',
    sub: "Women's Fashion",
    op: 2999,
    np: 2399,
    code: 'ASOS20',
    type: 'Coupon Deal',
    badges: ['COUPON'],
    h: 55,
    tags: ['dresses', 'women'],
    featured: true,
    clicks: 2100,
  },
]

// Computed deals — mirrors catalog.ts `deals` export exactly
const deals = dealSeeds.map((s, i) => ({
  id: `DL-${1000 + i}`,
  slug: slugify(s.t),
  title: s.t,
  product: s.p,
  product_id: null,
  brand: s.b,
  category: s.c,
  subcategory: s.sub ?? null,
  original_price: s.op,
  price: s.np,
  code: s.code ?? null,
  deal_type: s.type,
  badges: s.badges,
  description: `${brandName(s.b)} is offering ${s.p} at ${Math.round(((s.op - s.np) / s.op) * 100)}% off. ${
    s.code
      ? `Apply code ${s.code} at checkout to unlock the discounted price.`
      : 'The discount is applied automatically at checkout.'
  } Verified by our editors and updated daily.`,
  terms: [
    'Offer valid while stocks last on the merchant website.',
    'Discount applies to selected styles only; final price is shown at checkout.',
    s.code
      ? `Coupon code ${s.code} must be applied before payment.`
      : 'No coupon code required.',
    'Prices and availability are controlled by the merchant and may change without notice.',
  ],
  expires_in_hours: s.h,
  status: s.status ?? 'ACTIVE',
  image: `https://picsum.photos/seed/deal-${slugify(s.t)}/800/600`,
  tags: s.tags,
  merchant_url: `https://www.${s.b.replace(/-/g, '')}.com/${slugify(s.p)}`,
  network: getBrand(s.b)?.network ?? 'Admitad',
  campaign: `${s.c}-2026-q3`,
  sub_id: `web_${s.b}_${1000 + i}`,
  tracking_id: `TRK-${s.b.toUpperCase().slice(0, 4)}-${1000 + i}`,
  clicks: s.clicks,
  featured: !!s.featured,
  flash: !!s.flash,
  sponsored: !!s.sponsored,
}))

const coupons = [
  {
    id: 'C1',
    brand: 'nordstrom',
    title: 'Nordstrom Coupon',
    description: 'Get 20% OFF on selected fashion products sitewide.',
    code: 'STYLE20',
    discount: '20% OFF',
    expires_in_hours: 71,
    used_today: 412,
    success_rate: 92,
  },
  {
    id: 'C2',
    brand: 'nike',
    title: 'Nike Coupon',
    description: 'Extra 35% off on Air Max and Pegasus sneakers.',
    code: 'NIKE35',
    discount: '35% OFF',
    expires_in_hours: 46,
    used_today: 268,
    success_rate: 88,
  },
  {
    id: 'C3',
    brand: 'revolve',
    title: 'Revolve Coupon',
    description: 'Extra 25% off on already discounted styles.',
    code: 'REVOLVE25',
    discount: '25% OFF',
    expires_in_hours: 30,
    used_today: 530,
    success_rate: 95,
  },
  {
    id: 'C4',
    brand: 'zara',
    title: 'Zara Summer Code',
    description: 'Flat 40% off the summer linen edit.',
    code: 'SUMMER40',
    discount: '40% OFF',
    expires_in_hours: 48,
    used_today: 190,
    success_rate: 84,
  },
  {
    id: 'C5',
    brand: 'ulta',
    title: 'Ulta Beauty Coupon',
    description: 'Up to 50% off beauty plus free shipping over $12.',
    code: 'PINK50',
    discount: '50% OFF',
    expires_in_hours: 40,
    used_today: 377,
    success_rate: 90,
  },
  {
    id: 'C6',
    brand: 'sephora',
    title: 'Sephora Skincare Coupon',
    description: '25% off luxury skincare sets.',
    code: 'GLOW25',
    discount: '25% OFF',
    expires_in_hours: 90,
    used_today: 96,
    success_rate: 81,
  },
  {
    id: 'C7',
    brand: 'levis',
    title: "Levi's Denim Coupon",
    description: '45% off 501 Original Fit jeans.',
    code: 'DENIM45',
    discount: '45% OFF',
    expires_in_hours: 18,
    used_today: 224,
    success_rate: 87,
  },
  {
    id: 'C8',
    brand: 'puma',
    title: 'Puma Flash Coupon',
    description: 'Extra 30% off sale styles for 24 hours.',
    code: 'PUMA30',
    discount: '30% OFF',
    expires_in_hours: 8,
    used_today: 305,
    success_rate: 93,
  },
  {
    id: 'C9',
    brand: 'bata',
    title: 'Bata Footwear Coupon',
    description: 'Flat 50% off formal leather shoes.',
    code: 'BATA50',
    discount: '50% OFF',
    expires_in_hours: 110,
    used_today: 141,
    success_rate: 79,
  },
  {
    id: 'C10',
    brand: 'expedia',
    title: 'Expedia Stay Coupon',
    description: 'Extra 20% off US hotel bookings.',
    code: 'STAY20',
    discount: '20% OFF',
    expires_in_hours: 300,
    used_today: 88,
    success_rate: 76,
  },
  {
    id: 'C11',
    brand: 'charles-keith',
    title: 'Charles & Keith Coupon',
    description: 'Extra 20% off sale footwear and bags.',
    code: 'CK20',
    discount: '20% OFF',
    expires_in_hours: 34,
    used_today: 112,
    success_rate: 83,
  },
  {
    id: 'C12',
    brand: 'adidas',
    title: 'Adidas Track Coupon',
    description: '50% off Originals track jackets.',
    code: 'TRACK50',
    discount: '50% OFF',
    expires_in_hours: 22,
    used_today: 259,
    success_rate: 89,
  },
  {
    id: 'C13',
    brand: 'mango',
    title: 'Mango Coupon',
    description: '30% off tailored blazers and dresses.',
    code: 'MANGO30',
    discount: '30% OFF',
    expires_in_hours: 50,
    used_today: 145,
    success_rate: 85,
  },
  {
    id: 'C14',
    brand: 'columbia',
    title: 'Columbia Trail Coupon',
    description: '25% off outdoor jackets and footwear.',
    code: 'TRAIL25',
    discount: '25% OFF',
    expires_in_hours: 65,
    used_today: 98,
    success_rate: 80,
  },
  {
    id: 'C15',
    brand: 'asos',
    title: 'ASOS Design Coupon',
    description: 'Extra 20% off the ASOS Design edit.',
    code: 'ASOS20',
    discount: '20% OFF',
    expires_in_hours: 55,
    used_today: 210,
    success_rate: 88,
  },
]

const saleEvents = [
  {
    id: 'SE-1',
    store: 'nike-store',
    title: 'Nike Mid-Season Sale',
    discount: 'Up to 30% off',
    time_window: 'today',
    detail: 'Ends tonight — running and lifestyle silhouettes included.',
    code: 'NIKE30',
  },
  {
    id: 'SE-2',
    store: 'nordstrom',
    title: 'Nordstrom Fashion Hours',
    discount: 'Flat 50-70% off',
    time_window: 'today',
    detail: 'Marketplace-wide event with extra member offers.',
    code: null,
  },
  {
    id: 'SE-3',
    store: 'adidas-store',
    title: 'Adidas Originals Drop',
    discount: 'Up to 40% off',
    time_window: 'tomorrow',
    detail: 'Samba, Gazelle and Campus restock with sale pricing.',
    code: null,
  },
  {
    id: 'SE-4',
    store: 'ulta',
    title: 'Ulta Beauty Bonanza',
    discount: 'Up to 50% off',
    time_window: 'tomorrow',
    detail: 'Skincare bundles and prestige makeup.',
    code: 'PINK50',
  },
  {
    id: 'SE-5',
    store: 'zara-store',
    title: 'Zara End of Season Sale',
    discount: 'Up to 60% off',
    time_window: 'this-week',
    detail: 'Second markdown wave lands midweek.',
    code: null,
  },
  {
    id: 'SE-6',
    store: 'revolve',
    title: 'Revolve Big Bold Sale',
    discount: 'Extra 25% off',
    time_window: 'this-week',
    detail: 'Stacks on already reduced styles.',
    code: 'REVOLVE25',
  },
  {
    id: 'SE-7',
    store: 'footlocker',
    title: 'Foot Locker Sneaker Week',
    discount: 'Up to 35% off',
    time_window: 'next-week',
    detail: 'Nike, Adidas and Puma running styles.',
    code: null,
  },
  {
    id: 'SE-8',
    store: 'neiman-marcus',
    title: 'Neiman Marcus Luxury Edit',
    discount: 'Up to 45% off',
    time_window: 'next-week',
    detail: 'Watches, bags and premium beauty.',
    code: null,
  },
  {
    id: 'SE-9',
    store: 'amazon',
    title: 'Amazon Fashion Days',
    discount: 'Up to 70% off',
    time_window: 'this-month',
    detail: 'Category-wide event across apparel and footwear.',
    code: null,
  },
  {
    id: 'SE-10',
    store: 'decathlon',
    title: 'Decathlon Fitness Fest',
    discount: 'Up to 30% off',
    time_window: 'this-month',
    detail: 'Home gym, running and travel gear.',
    code: null,
  },
  {
    id: 'SE-11',
    store: 'hm-store',
    title: 'H&M Member Days',
    discount: 'Extra 20% off',
    time_window: 'this-month',
    detail: 'Members-only pricing across basics and home.',
    code: null,
  },
]

// Map JS-style keys -> DB column names for brands/stores (source objects use
// camelCase for a couple of fields; DB columns are snake_case)
const brandsForDb = brands.map((b) => ({
  slug: b.slug,
  name: b.name,
  description: b.description ?? null,
  category: b.category ?? null,
  network: b.network,
  featured: !!b.featured,
}))

const storesForDb = stores.map((s) => ({
  slug: s.slug,
  name: s.name,
  description: s.description ?? null,
  network: s.network,
  domain: s.domain,
  campaign: s.campaign,
  store_id: s.storeId,
  sub_id: s.subId,
  ships_to: s.shipsTo,
  store_wide_offer: s.storeWideOffer ?? null,
  featured: !!s.featured,
  sponsored: !!s.sponsored,
}))

module.exports = { brandsForDb, storesForDb, deals, coupons, saleEvents }
